<?php

namespace Application\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function getAllUserAndLastComment()
    {

  //       return $this->createQueryBuilder('u')
  //       ->where('u.login = :log AND u.password = :pas')
  //       ->setParameter('log', $login)
		// ->setParameter('pas', $password)
		// ->getQuery()
  //       ->getResult();
    }
}
